FROM debian:bookworm

ARG DEBIAN_FRONTEND=noninteractive
ENV GOLANG_VERSION=1.26.0
ENV PATH="/usr/local/go/bin:${PATH}"
ENV CGO_ENABLED=0

RUN apt update && apt install -y --no-install-recommends git curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://go.dev/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz -o /tmp/go.tgz

RUN tar -C /usr/local -xzf /tmp/go.tgz

RUN rm /tmp/go.tgz

WORKDIR /opt/golosok

COPY . .

RUN mkdir -p build && GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o build/golosok.exe ./cmd/golosok