FROM debian:bookworm AS build

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y --no-install-recommends build-essential git cmake automake autoconf libtool \
    pkg-config zlib1g-dev ca-certificates python3 python3-dev unzip wget curl sox subversion gfortran \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN git clone -b vosk --single-branch --depth=1 https://github.com/alphacep/kaldi

RUN git clone --depth=1 https://github.com/alphacep/vosk-api

# Kaldi

WORKDIR /opt/kaldi/tools

RUN make -j"$(nproc)" openfst cub

RUN ./extras/install_openblas_clapack.sh

WORKDIR /opt/kaldi/src

RUN ./configure --mathlib=OPENBLAS_CLAPACK --shared

RUN make -j"$(nproc)" online2 lm rnnlm

# Vosk api

WORKDIR /opt/vosk-api/src

RUN KALDI_ROOT=/opt/kaldi make -j"$(nproc)"

RUN install -Dm755 libvosk.so /opt/out-vosk/lib/libvosk.so \
    && install -Dm644 vosk_api.h /opt/out-vosk/include/vosk_api.h